In [51]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler,MinMaxScaler,OneHotEncoder
#from sklearn.compose import ColumnTransformer
#from sklearn.pipeline import Pipeline
#from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest,f_regression,f_classif
#from sklearn.decomposition import PCA

In [52]:
df=pd.read_csv("auto-mpg.csv")

display(df.head())

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [53]:
print(df.dtypes)

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [54]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [55]:
#To automatically find numeric columns
numeric_columns=df.select_dtypes(include=np.number).columns

print("Numeric Columns:")
print(numeric_columns)

#origin is often represented by numbers such as 1,2,3
#so technically pandas may identify it as numeric
#even though it represents categories.

Numeric Columns:
Index(['mpg', 'cylinders', 'displacement', 'weight', 'acceleration',
       'model year', 'origin'],
      dtype='object')

In [56]:
#To automatically find categorical columns:
categorical_columns=df.select_dtypes(include="object").columns

print("Categorical Columns:")
print(categorical_columns)

Categorical Columns:
Index(['horsepower', 'car name'], dtype='object')

In [57]:
df["origin"]=df["origin"].astype("object")

In [58]:
#First Check missing values:
print(df.isnull().sum())

#Auto-MPG commonly represents missing horsepower values using?.
#So first convert ? into missing value:

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [59]:
df["horsepower"]=pd.to_numeric(df["horsepower"].replace("?",np.nan),errors="coerce")

df["horsepower"]=df["horsepower"].replace(np.nan,df["horsepower"].mean())

print(df.isnull().sum())

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [60]:
scaler=MinMaxScaler().set_output(transform="pandas")

scaled_data=scaler.fit_transform(df[numeric_columns])

scaled_data.head()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
0,0.239362,1.0,0.617571,0.536150,0.238095,0.0,0.0
1,0.159574,1.0,0.728682,0.589736,0.208333,0.0,0.0
2,0.239362,1.0,0.645995,0.516870,0.178571,0.0,0.0
3,0.186170,1.0,0.609819,0.516019,0.238095,0.0,0.0
4,0.212766,1.0,0.604651,0.520556,0.148810,0.0,0.0

In [61]:
#Suppose mpg is our target

X=df.drop("mpg",axis=1)
y=df["mpg"]

In [62]:
#For a simple numerical example, we can select the best 5 features:

X_numeric=X.select_dtypes(include=np.number)

selector=SelectKBest(
    score_func=f_regression,
    k=5
).set_output(transform="pandas")

X_selected=selector.fit_transform(X_numeric,y)

print(X_selected.head())

   cylinders  displacement  horsepower  weight  model year
0          8         307.0       130.0    3504          70
1          8         350.0       165.0    3693          70
2          8         318.0       150.0    3436          70
3          8         304.0       150.0    3433          70
4          8         302.0       140.0    3449          70